In [1]:
import os
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
ROOT_PATH = "dataset"
REVIEW_PATH = "beauty/Beauty_and_Personal_Care.jsonl"
META_PATH = "beauty/meta_Beauty_and_Personal_Care.jsonl"

NEG_ITEM = 10

In [3]:
def load_df(path):
    return pd.read_json(path, lines=True)

## Load Data

In [4]:
# interaction data
# review_df = load_df(os.path.join(ROOT_PATH, REVIEW_PATH))
review_df = pd.read_json(os.path.join(ROOT_PATH, REVIEW_PATH), lines=True, nrows=100000)
review_df.head(n=5)

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,1,Gasoline!! Seriously reeks of gasoline!,Opened the package & instant migraine. I canno...,[{'small_image_url': 'https://images-na.ssl-im...,B00Z03RC80,B00Z03RC80,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2021-03-26 07:24:14.733,0,True
1,1,Useless! These have massive gaps at pump nozzle.,Tops the list for worst purchase. Tried these ...,[{'small_image_url': 'https://images-na.ssl-im...,B085PRT2MP,B085PRT2MP,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2021-03-05 03:46:17.684,0,True
2,5,Hailey loves unicorns!,Bought this for my granddaughter. Her entire ...,[],B08G81QQ9L,B08G81QQ9L,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2021-01-31 00:21:33.701,0,True
3,1,Not sharp enough to cut smoothly.,These are extremely dull and will wreck your n...,[],B07YYG76X1,B07YYG76X1,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2021-01-03 19:09:41.786,0,True
4,3,"Pretty, but didn’t close correctly.",Mine wouldn’t close correctly so I sent it bac...,[],B0761M33BX,B07X4FKLNK,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2020-02-10 05:39:55.358,0,True

In [5]:
# item data
# meta_df = load_df(os.path.join(ROOT_PATH, META_PATH))
meta_df = pd.read_json(os.path.join(ROOT_PATH, META_PATH), lines=True, nrows=100000)
meta_df.head(n=5)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,All Beauty,"Shiyeen 10 Colors Hair Chalk for Girls Gift, K...",3.9,57,"[🌼[MEET YOUR HAIR COLOR NEEDS] Bright color, h...",[],None,[{'thumb': 'https://m.media-amazon.com/images/...,[],shiyeen,"[Beauty & Personal Care, Hair Care, Hair Color...","{'Color': 'Orange,Blue,Cyan,White,Green,Red,Pi...",B08BLDKYHB,NaN,NaN,NaN
1,All Beauty,"Ebbfurln Bob Wig Human Hair, 13x4 HD Lace Fron...",4.1,60,[Frontal Wigs Human Hair Material: 100% unproc...,[],45.65,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Cute bob', 'url': 'https://www.ama...",Ebbfurln,"[Beauty & Personal Care, Hair Care, Hair Exten...","{'Color': '13x4 Bob Wigs', 'Material': 'Human'...",B0BWJGQ32Y,NaN,NaN,NaN
2,All Beauty,Makeup brush cleaner and dryer electronic spin...,4.4,7,[],[],None,[{'thumb': 'https://m.media-amazon.com/images/...,[],J-ANKKA,"[Beauty & Personal Care, Tools & Accessories, ...","{'Is Discontinued By Manufacturer': 'No', 'Pac...",B07DC9S9PF,NaN,NaN,NaN
3,All Beauty,"3 Inch Clipper Guards, Hair Clipper Guide Comb...",4.0,68,[3 Inch Clipper Guards: The only 3 inch hair c...,[],24.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Wahl Clipper Guards NO.16 NO.12 NO...,CR8GR8,"[Beauty & Personal Care, Hair Care, Hair Cutti...","{'Recommended Uses For Product': 'Clipping', '...",B0BM8WLSXF,NaN,NaN,NaN
4,All Beauty,Cathy Doll L-Glutathione Magic Cream SPF 50 Wh...,4.0,65,[Magic Cream is formulated with an additional ...,"[Extend the flawless, smooth complexion from f...",14.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'MCHOIX Sunscreen SPF 50 ', 'url': ...",Cathy Doll,"[Beauty & Personal Care, Skin Care, Sunscreens...","{'Product Benefits': 'Whitening', 'Sun Protect...",B00N4LMZZK,NaN,NaN,NaN

In [6]:
# Filter the products with user-interactions
interact_meta_df = meta_df[meta_df["parent_asin"].isin(review_df["parent_asin"])].reset_index(drop=True)
interact_meta_df.head(n=5)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,All Beauty,"L.A. COLORS 5 Color Matte Eyeshadow, Brown Twe...",4.3,5367,"[Intense color, Matte finish, Silky texture]","[Wrap yourself in soft, cozy color. These matt...",2.49,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'LA Colors Pallete Review - YOU MUS...,L.A. COLORS,"[Beauty & Personal Care, Makeup, Eyes, Eyeshadow]","{'Color': 'Brown Tweed', 'Brand': 'L.A. COLORS...",B01DX1OEFO,NaN,NaN,NaN
1,All Beauty,Newcally Natural Look Lashes Mink 3D Fluffy Wi...,4.4,34981,[The natural false eyelashes are fluffy and so...,[],9.45,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'My favorite lashes ', 'url': 'http...",Newcally,"[Beauty & Personal Care, Tools & Accessories, ...","{'Color': 'Black', 'Brand': 'Newcally', 'Mater...",B09WHMND5W,NaN,NaN,NaN
2,All Beauty,Okbool Professional Easy to Use Stainless Stee...,4.0,155,[HIGH QUALITY: Stainless steel nail clippers s...,[],None,[{'thumb': 'https://m.media-amazon.com/images/...,[],okbool,"[Beauty & Personal Care, Foot, Hand & Nail Car...","{'Color': '3pcs Set', 'Brand': 'Okbool', 'Mate...",B07PMB849J,NaN,NaN,NaN
3,Health & Personal Care,Babo Botanicals Sheer Zinc Continuous Spray Su...,4.3,4526,[100% GOOD FOR YOU & YOUR FAMILY: A fast-absor...,[Get the comfort of a lotion sunscreen and the...,18.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Be Aware! Very Watery, Do Not Reco...",Babo Botanicals,"[Beauty & Personal Care, Skin Care, Sunscreens...","{'Scent': 'Unscented', 'Product Benefits': 'Fa...",B01ALT5MKW,NaN,NaN,NaN
4,All Beauty,Aerin Rose Hand & Body Cream 0.5 oz - Deluxe T...,3.5,8,[],[],15.98,[{'thumb': 'https://m.media-amazon.com/images/...,[],AERIN,"[Beauty & Personal Care, Foot, Hand & Nail Car...","{'Brand': 'AERIN', 'Scent': 'Rose', 'Item Form...",B00DK7FX4S,NaN,NaN,NaN

## Statistic

In [7]:
user_num = review_df["user_id"].nunique()
item_num = review_df["parent_asin"].nunique()
item_num_meta_without_filter = meta_df["parent_asin"].nunique()
num_interactions = len(review_df)
start_time = review_df["timestamp"].min()
end_time = review_df["timestamp"].max()

In [8]:
time_format = "%Y-%m-%d"
print(f"user number: {user_num}")
print(f"item number: {item_num}")
print(f"item number in meta without filter: {item_num_meta_without_filter}")
print(f"number of interactions: {num_interactions}")
print(f"start time: {start_time}")
print(f"end time: {end_time}")

user number: 10176
item number: 57316
item number in meta without filter: 100000
number of interactions: 100000
start time: 2000-12-20 01:09:42
end time: 2023-03-17 06:50:15.185000

In [9]:
print(review_df["timestamp"].dtype)

datetime64[ms]

## Build Dataset

In [10]:
history_df = review_df.rename(columns={"timestamp": "time"})
history_df = history_df[["user_id", "parent_asin", "time"]]
history_df["time"] = history_df["time"].astype(int)
history_df.drop_duplicates(inplace=True)
history_df = history_df.sort_values(by=["time", "user_id"], kind="mergesort").reset_index(drop=True)
history_df.head(n=5)

                        user_id parent_asin           time
0  AGWDYYVVWM3DC3CASUZKXK67G6IA  B000050FET   977274582000
1  AGWDYYVVWM3DC3CASUZKXK67G6IA  B09JRQYJYW  1023918861000
2  AGWDYYVVWM3DC3CASUZKXK67G6IA  B00005REB0  1024288944000
3  AGWDYYVVWM3DC3CASUZKXK67G6IA  B09FFKML75  1024290745000
4  AGWDYYVVWM3DC3CASUZKXK67G6IA  B098XL768K  1024290979000

In [11]:
uid_set = sorted(history_df["user_id"].unique())
uid2id = {uid: id for id, uid in enumerate(uid_set)}
iid_set = sorted(history_df["parent_asin"].unique())
iid2id = {iid: id for id, iid in enumerate(iid_set)}

history_df["user_id"] = history_df["user_id"].apply(lambda x: uid2id[x])
history_df["parent_asin"] = history_df["parent_asin"].apply(lambda x: iid2id[x])
history_df.head(n=5)

   user_id  parent_asin           time
0     7357           17   977274582000
1     7357        43678  1023918861000
2     7357           86  1024288944000
3     7357        42698  1024290745000
4     7357        41364  1024290979000

In [12]:
# leave one out evaluation 留一法评估，用户序列最后一个和倒数第二个 item 取出，作为 eval 和 test 的正样本，其余作为 train

# 用户点击合集，用于后续的负采样
user_click_item_set = dict()
for user_id, item_seq in history_df.groupby("user_id"):
    user_click_item_set[user_id] = set(item_seq["parent_asin"].values.tolist())

def gen_3_set(df):
    eval_test = []
    item_num = df["parent_asin"].value_counts().size
    df = df.groupby("user_id").filter(lambda x: len(x) >= 3)
    for i in range(2):
        temp_df = df.groupby("user_id").tail(1).copy()
        df = df.drop(temp_df.index)
        neg_items = np.random.randint(0, item_num - 1, size=(len(temp_df), NEG_ITEM))
        for i, uid in enumerate(temp_df["user_id"].values):
            user_clicked = user_click_item_set[uid]
            for j in range(len(neg_items[i])):
                while neg_items[i][j] in user_clicked:
                    neg_items[i][j] = np.random.randint(0, item_num - 1)
        temp_df["neg_items"] = neg_items.tolist()
        eval_test.append(temp_df)
    return eval_test, df

In [13]:
# 保底每个用户都有一个交互记录
guarantee_set = history_df.groupby("user_id").head(1)
history_df = history_df.drop(guarantee_set.index)

[eval_data, test_data], train_data = gen_3_set(history_df)
train_data = pd.concat([train_data, guarantee_set]).sort_index()

print(f"train data: {len(train_data)}, eval data: {len(eval_data)}, test data: {len(test_data)}")

train data: 87396, eval data: 4292, test data: 4292

In [14]:
train_data.head(n=5)

   user_id  parent_asin           time
0     7357           17   977274582000
1     7357        43678  1023918861000
2     7357           86  1024288944000
3     7357        42698  1024290745000
4     7357        41364  1024290979000

In [15]:
eval_data.head(n=5)

,user_id,parent_asin,time,neg_items
667,318,26910,1317265141000,"[28370, 992, 18301, 34325, 29299, 35610, 18235..."
1108,4145,20917,1352493485000,"[34506, 45295, 25323, 4316, 20524, 16344, 3374..."
1842,6420,864,1371767417000,"[36227, 44297, 938, 8944, 44639, 52130, 24939,..."
2013,9144,1206,1376543088000,"[11642, 15922, 9334, 23699, 31897, 25569, 9167..."
2044,8331,6314,1377291823000,"[26818, 18483, 25169, 48543, 47199, 13505, 400..."

In [16]:
test_data.head(n=5)

,user_id,parent_asin,time,neg_items
247,318,22425,1216692872000,"[35280, 37644, 2923, 40126, 2607, 17151, 22109..."
1054,2705,10795,1348653497000,"[769, 49870, 49772, 6342, 36930, 46570, 47422,..."
1072,1717,12497,1349936564000,"[49399, 16634, 1749, 22938, 39994, 10149, 1657..."
1107,4145,5358,1352493303000,"[14934, 22831, 7134, 37214, 4710, 5359, 33630,..."
1354,274,4693,1360247822000,"[18484, 28233, 22076, 17574, 7719, 5365, 3957,..."

In [17]:
# save 3 sets
train_data.to_csv(os.path.join(ROOT_PATH, "train_data.csv"), index=False)
eval_data.to_csv(os.path.join(ROOT_PATH, "eval_data.csv"), index=False)
test_data.to_csv(os.path.join(ROOT_PATH, "test_data.csv"), index=False)

### Item data

In [18]:
item_df = interact_meta_df[[
    "title", 
    "average_rating",
    "rating_number",
    "features",
    "description",
    "price",
    "categories", 
    "details",
    "parent_asin"
    ]]
item_df["parent_asin"] = item_df["parent_asin"].apply(lambda x: iid2id[x])
item_df["l1_category"] = item_df["categories"].apply(lambda x: x[0] if len(x) > 0 else "")
item_df["l2_category"] = item_df["categories"].apply(lambda x: x[1] if len(x) > 1 else "")
item_df["l3_category"] = item_df["categories"].apply(lambda x: x[2] if len(x) > 2 else "")
item_df.drop(columns=["categories"], inplace=True)
item_df["features"] = item_df["features"].apply(lambda x: " ".join(x) if isinstance(x, list) else "")
item_df["description"] = item_df["description"].apply(lambda x: " ".join(x) if isinstance(x, list) else "")
# convert dict to string
item_df["details"] = item_df["details"].apply(lambda x: " ".join([f"{k}: {v}" for k, v in x.items()]) if isinstance(x, dict) else "")
item_df.head(n=5)

,title,average_rating,rating_number,features,description,price,details,parent_asin,l1_category,l2_category,l3_category
0,"L.A. COLORS 5 Color Matte Eyeshadow, Brown Twe...",4.3,5367,Intense color Matte finish Silky texture,"Wrap yourself in soft, cozy color. These matte...",2.49,Color: Brown Tweed Brand: L.A. COLORS Item For...,14345,Beauty & Personal Care,Makeup,Eyes
1,Newcally Natural Look Lashes Mink 3D Fluffy Wi...,4.4,34981,The natural false eyelashes are fluffy and sof...,,9.45,Color: Black Brand: Newcally Material: Plastic...,46874,Beauty & Personal Care,Tools & Accessories,Makeup Brushes & Tools
2,Okbool Professional Easy to Use Stainless Stee...,4.0,155,HIGH QUALITY: Stainless steel nail clippers se...,,None,Color: 3pcs Set Brand: Okbool Material: Stainl...,25418,Beauty & Personal Care,"Foot, Hand & Nail Care",Tools & Accessories
3,Babo Botanicals Sheer Zinc Continuous Spray Su...,4.3,4526,100% GOOD FOR YOU & YOUR FAMILY: A fast-absorb...,Get the comfort of a lotion sunscreen and the ...,18.99,Scent: Unscented Product Benefits: Fast-absorb...,13696,Beauty & Personal Care,Skin Care,Sunscreens & Tanning Products
4,Aerin Rose Hand & Body Cream 0.5 oz - Deluxe T...,3.5,8,,,15.98,Brand: AERIN Scent: Rose Item Form: Cream Unit...,7883,Beauty & Personal Care,"Foot, Hand & Nail Care",Foot & Hand Care

In [19]:
item_df.to_csv(os.path.join(ROOT_PATH, "item_df.csv"), index=False)